//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYKHOEntities1 : DbContext
    {
        public QUANLYKHOEntities1()
            : base("name=QUANLYKHOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<INPUT> INPUTs { get; set; }
        public virtual DbSet<INPUTINFO> INPUTINFOes { get; set; }
        public virtual DbSet<OBJECTSS> OBJECTSSes { get; set; }
        public virtual DbSet<OUTPUT> OUTPUTs { get; set; }
        public virtual DbSet<OUTPUTINFO> OUTPUTINFOes { get; set; }
        public virtual DbSet<SUPLIER> SUPLIERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UNIT> UNITs { get; set; }
        public virtual DbSet<USERROLE> USERROLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
